source "https://rubygems.org"

ruby "3.3.0" 

gem "rails", "~> 7.2.1" # Versão estável da série 7.2
gem "pg", "~> 1.5"      # Versão mais recente e estável do driver Postgres
gem "puma", "~> 6.4"    # Puma 6 é a recomendada para Rails 7.2+

gem "pg_search", "~> 2.3"
gem "rack-cors"

# Gems de suporte do Rails 7.2
gem "tzinfo-data", platforms: %i[ windows jruby ]
gem "solid_cache"
gem "solid_queue"
gem "solid_cable"
gem "bootsnap", require: false
gem "image_processing", "~> 1.2"

group :development, :test do
  gem "debug", platforms: %i[ mri windows ]
  gem "minitest", "~> 5.25" 
end

group :development do
  gem "bundler-audit", require: false
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
end

group :test do
  # Ajuda a limpar a base de dados entre testes
  gem "database_cleaner", "~> 2.0"
end